server:
  port: 2000
  context-path: /
logging:
  file: /kation-cloud/logs/doc/system.log  # 日志文件,绝对路径或相对路径
  path: /kation-cloud/logs/doc  # 保存日志文件目录路径
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
spring:
  cloud:
    config:
      profile: dev
      lable: master
      url: http://127.0.0.1:8888/
  application:
    name: doc-service
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60   # 发呆时间，即服务续约到期时间（缺省为90s）
    status-page-url-path: /info
    health-check-url-path:  /health
  client:
    healthcheck:
        enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kation:123456@127.0.0.1:8761/eureka
security: 
  basic:
    enabled: false
hystrix:
  metrics:
    polling-interval-ms: 5000