server:
  port: 2000
  context-path: /
logging:
  file: /Users/kationwang/Desktop/JavaShell.log  # 日志文件,绝对路径或相对路径
  path: /Users/kationwang/Desktop  # 保存日志文件目录路径
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
spring:
  datasource:
    doc:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://118.89.148.123:3306/doc
      username: root
      password: mydrn123
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 10
      maxActive: 30
      timeBetweenEvictionRunsMillis: 36000000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  jpa:  
    database : MYSQL  
    show-sql : true
    format-sql : true
    hibernate:  
      ddl-auto: update  
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy  
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect 
  application:
    name: doc-service
  profiles:
    active: bendi
  redis:
      database: 13        #Redis数据库索引（默认为0）
      host: 139.196.51.84 #Redis服务器地址
      port: 6379          # Redis服务器连接端口
      password:           # Redis服务器连接密码（默认为空）
      pool:
        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8       # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
      timeout: 0          # 连接超时时间（毫秒）

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60   # 发呆时间，即服务续约到期时间（缺省为90s）
    status-page-url-path: ${server.context-path}/info
    health-check-url-path:  ${server.context-path}/health
  client:
    healthcheck: 
        enabled: true 
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://kation:123456@118.89.148.123/eureka
security: 
  basic:
    enabled: false
hystrix:
  metrics:
    polling-interval-ms: 5000