security:
  basic:
    enabled: true
  user:
    name: kation
    password: 123456
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false           # \u5173\u95ED\u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F\uFF08\u7F3A\u7701\u4E3A\u6253\u5F00\uFF09
    eviction-interval-timer-in-ms: 60000       # \u7EED\u671F\u65F6\u95F4\uFF0C\u5373\u626B\u63CF\u5931\u6548\u670D\u52A1\u7684\u95F4\u9694\u65F6\u95F4\uFF08\u7F3A\u7701\u4E3A60*1000ms\uFF09
  client:
    healthcheck:
        enabled: true 
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://kation:123456@localhost:8761/eureka
